"""init

Revision ID: 945cea3d8641
Revises: 
Create Date: 2023-12-08 22:37:12.841049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '945cea3d8641'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('login_user', sa.String(length=50), nullable=False),
    sa.Column('bill', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('user_role', sa.String(), server_default='user', nullable=False),
    sa.CheckConstraint("user_role IN ('user', 'creator', 'admin')", name='check_user_role'),
    sa.CheckConstraint('LENGTH(login_user) >= 5', name='check_login_length'),
    sa.CheckConstraint('LENGTH(password) >= 5', name='check_password_length'),
    sa.PrimaryKeyConstraint('login_user')
    )
    op.create_table('Product',
    sa.Column('id_product', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('creation_date', sa.Date(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('genre', sa.Text(), nullable=False),
    sa.Column('vers', sa.Float(), nullable=False),
    sa.Column('main_product', sa.Integer(), nullable=True),
    sa.Column('login_user', sa.String(length=50), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.CheckConstraint('main_product IS NULL OR main_product != id_product', name='check_main_product'),
    sa.CheckConstraint('price >= 0', name='control_price'),
    sa.ForeignKeyConstraint(['login_user'], ['User.login_user'], ),
    sa.ForeignKeyConstraint(['main_product'], ['Product.id_product'], ),
    sa.PrimaryKeyConstraint('id_product'),
    sa.UniqueConstraint('title')
    )
    op.create_table('Transaction',
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('login_user', sa.String(length=50), nullable=False),
    sa.Column('final_price', sa.Integer(), nullable=False),
    sa.Column('trans_datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint('final_price >= 0', name='final_price_check'),
    sa.ForeignKeyConstraint(['id_product'], ['Product.id_product'], ),
    sa.ForeignKeyConstraint(['login_user'], ['User.login_user'], ),
    sa.PrimaryKeyConstraint('id_product', 'login_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Transaction')
    op.drop_table('Product')
    op.drop_table('User')
    # ### end Alembic commands ###
